### ISSUE TITLE
Reception - Terminate a kitchen after 5 seconds of inactivity

### ISSUE THREAD

**Issue by Cavonstavant** [Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA#133]
Add a field inside the status message that will represent the time that ellapsed since the last command that was sent to the pizza.
If the ellapsed time is over or equal to 5, send exit to the kitchen.

**Comment by Cavonstavant** [comment]
In order to differentiate the exit after the command `exit` and after 5 seconds of inactivity, it would be best to use separate signals such as `SIGTERM` for `exit` and `SIGUSR1` for the later.

**Comment by osvegn** [comment]
Duplicata of #131.
