### ISSUE TITLE
Error Handling - Parse the received command

### ISSUE THREAD

**Issue by 31Nathan** [Cavonstavant/PLAZAAAAAAAAAAAAAAAAAAAAAAA#4]
Parse the received command
Create a class to parse and send the current command
If the command isn't valid, throw an error message, don't quit the program

**Comment by osvegn** [comment]
See the following exemple:
Margarita XL; Margarita L x1
This command will say : "First command is invalide", and prossess the second command
or
this command will say : "Invalide command" ?

**Comment by osvegn** [comment]
See the following exemple:
Margarita XL x1;;;;Margarita XL x1
Is it possible to have multiple separator ?

**Comment by Cavonstavant** [comment]
> See the following exemple: Margarita XL; Margarita L x1 This command will say : "First command is invalide", and prossess the second command or this command will say : "Invalide command" ?

imo we have to log the bad command and process the other

**Comment by Cavonstavant** [comment]
> See the following exemple: Margarita XL x1;;;;Margarita XL x1 Is it possible to have multiple separator ?

Assume yes
